/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_coderodde_os_beep_WindowsBeep */

#ifndef _Included_net_coderodde_os_beep_WindowsBeep
#define _Included_net_coderodde_os_beep_WindowsBeep
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     net_coderodde_os_beep_WindowsBeep
     * Method:    beep
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_net_coderodde_os_beep_WindowsBeep_beep
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
